name: cd-prod

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: Deploy latest changes
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.AWS_CSO_MANAGER_INSTANCE_IP}}
          USER_NAME: ${{secrets.AWS_CSO_MANAGER_INSTANCE_USER}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              ls
              '
